---
title: "flowr"
subtitle: "Streamlining Workflows"
author: Sahil Seth
copyright: Sahil Seth
output:
  packagedocs:
    toc: true
rd_page: true
navpills: |
  <li><a href='docs.html'>Overview</a></li>
  <li><a href='install.html'>Install</a></li>
  <li><a href='tutorial.html'>Tutorial</a></li>
  <li class="active"><a href='rd.html'>Help</a></li>
  <li><a href='news.html'>News</a></li>
  <li><a href='https://github.com/sahilseth/flowr'>Github <i class='fa fa-github'></i></a></li>
---

<div class="alert alert-success" role="alert">
You may download a PDF version of this manual [here](manual.pdf)
</div>
<h1>Streamlining Design and Deployment of Complex Workflows</h1>

<p><strong>Authors:</strong> <a href="mailto:me@sahilseth.com">Sahil Seth</a> [aut, cre]</p>
<p><strong>Version:</strong> 0.9.7.9031</p>
<p><strong>License:</strong> MIT + file LICENSE</p>

<h4>Description</h4>
<p>
This framework allows you to design and implement complex pipelines, and
deploy them on your institution's computing cluster. This has been built
keeping in mind the needs of bioinformatics workflows. However, it is
easily extendable to any field where a series of steps (shell commands)
are to be executed in a (work)flow.</p>

<h4>Depends</h4>
<p>
R (>= 3.0.2),
methods,
params  (>= 0.2.8),
utils</p>

<h4>Imports</h4>
<p>
diagram,
whisker,
tools</p>

<h4>Suggests</h4>
<p>
reshape2,
knitr,
ggplot2,
openxlsx,
testthat</p>

<h4>Enhances</h4>
<p>(none)</p>

# Creating a Flow

# Submiting and managing a flow

# Managing parameters

# Managing pipelines

# Details on flowr's classes

# Other helpful functions


