---
title: "tests.Rmd"
output: html_document
---


```
module load R git
git clone git@github.com:sahilseth/flowr.git

## test for roel
cd ~/apps
rm -rf ~/apps/flowr
git clone https://github.com/sahilseth/flowr.git
R CMD INSTALL flowr
flowr run sleep execute=TRUE platform=torque

## HMS test
install.flow; flowr run sleep platform=lsf execute=TRUE

Rscript -e 'flowr:::.run_sleep(platform = "moab", execute=TRUE)'
```



```{r}
devtools::install_github("sahilseth/flowr")
library(flowr)
setup()
```


```{r}
setwd("~/Dropbox/public/github_flow/")
devtools::load_all(".")
```


```{r}
library(flowr)
setup()

platform = "torque"
platform = "lsf"
platform = "moab"


fobj = flowr:::.run_sleep(platform = platform)
fobj = flowr:::.run_sleep(platform = platform, execute=TRUE)

```


```{r}

fobj = .run_sleep() ## should be local
fobj@jobs[[1]]@platform == "local"
fobj = .run_sleep(execute = TRUE)


fobj = .run_sleep(platform = "lsf") ## should be local
fobj = .run_sleep(platform = "sge") ## should be local
fobj = .run_sleep(platform = "moab") ## should be local


```


## test that script renders properly
```{r}
#exdata = file.path(system.file(package = "flowr"), "extdata")
exdata = "~/Dropbox/public/github_flow/inst/extdata"
flow_mat = read_sheet(file.path(exdata, "example1_flow_mat.txt"))
flow_mat = subset(flow_mat, samplename == "sample1")
flow_def = read_sheet(file.path(exdata,  "example1_flow_def.txt"))

## remove memory, should detect and throw error:
#colnames(flow_def)[6] = "mem"
#debug(render_queue_cmd)

flowr:::check.flow_def(flow_def)

fobj = to_flow(x = flow_mat, def = flow_def, submit = TRUE, platform = "lsf")

```


## test to_flow
```{r}
extdata = file.path(system.file(package = "flowr"), "extdata")
ex = file.path(system.file(package = "flowr"), "examples")
flow_mat = read_sheet(file.path(ex, "sleep_pipe.tsv"))
flow_def = read_sheet(file.path(ex, "sleep_pipe.def"))

fobj <- to_flow(x = flow_mat, def = as.flowdef(flow_def), 
	flowname = "example1", platform = "lsf", execute = t)

fobj <- to_flow(x = as.flowmat(flow_mat), def = as.flowdef(flow_def), 
	flowname = "example1", platform = "lsf")

```


