---
title: "flowr simple examples"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{flowr simple example}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Simple flow

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  error = FALSE,
  tidy = FALSE
)
library(flowr)
```

### Assuming we are working on a LSF platform, we define it using type. Currently we support LSF and Torque (SGE). 
```{r getqobj}
qobj <- queue(type = "lsf", queue = "normal")
```

### creating a pipeline definition: Style1
```{r plot_simpleflow}
job1 <- job(name = "myjob1", cmds = "sleep1", q_obj = qobj)
job2 <- job(name = "myjob2", cmds = "sleep2", q_obj = qobj, previous_job = "myjob1", dependency_type = "serial")
job3 <- job(name = "myjob3", cmds = "sleep3", q_obj = qobj, previous_job = "myjob1", dependency_type = "serial")
fobj <- flow(name = "myflow", jobs = list(job1, job2, job3), desc="description")
#source('/DRIVES/Dropbox2/Dropbox/public/github_flow/R/plot-funcs.R')
plot_flow(fobj)
```

```{r}
dat <- flowr:::.create_jobs_mat(fobj)
knitr:::kable(dat)
```

For more details look at [Building flowr recepies](buid_main.html)
